### ISSUE TITLE
Performanceprobleme bei Szenariotesting

### ISSUE THREAD

**Issue by aaronschweig** [Stonks2Moon/Boerse#37]
Hallo Börsenteam!

Wir haben gerade versucht einige unserer Szenarien durchzutesten. Wir haben dabei eine Last von ca. 22 req/s generiert. Sobald diese Szenarien beim Server ankommen konnten wir eine CPU Auslastung von 60%+ feststellen, was, sofern wir das Szenario weiterlaufen ließen, zum Absturz des Services führte.

Wir haben daraufhin einmal kurz in deinen Code geschaut und wir haben festgestellt, dass evtl. die Callbacks einen Anteil an dem Problem haben können. Vllt wäre es mal einen Versuch wert die Callbacks erst am Ende der Verarbeitung **und vor allem optional** abzufeuern. Das könnte helfen. Zusätzlich wäre es mal interessant den Code generell zu untersuchen, ob an manchen Stellen anstatt in Memory operationen durchzuführen dinge auf Datenbank oder Cache level erledigt werden können (z.B. Sortieren, o.ä.)

Wir konnten unseren Test also leider nicht erfolgreich beenden und hoffen, dass noch etwas an der Performance gemacht werden kann, um die Szenarien zu ermöglichen!

LG das Szenarioteam

**Comment by TimoScheuermann** [comment]
Erste Improvements sind eingebaut.

Weitere wurden erkannt und werden demnächst implementiert.

LG das StonksManager Team

**Comment by TimoScheuermann** [comment]
Version 1.5 hat weitere mögliche Performance Verbesserungen mit sich gebracht.

@aaronschweig bitte prüfen und danach ggf. dieses issue schließen 

Lg

**Comment by jangruebener** [comment]
@TimoScheuermann @JeannineB @Salocinf @egerj @Velii 

Wir haben weiterhin Performance Probleme bei der Durchführung unserer Szenarios und brauchen deshalb eure Unterstützung. Selbst bei Szenarios mit geringer Auslastung (44 Requests / Sekunde) findet das Matching erst zeitversetzt statt. 

Bsp.: Wir haben vorher ein Szenario getestet. Während des Szenarios wurden kaum gematched. Die CPU Auslastung auf dem Server ging dabei auf über 20 % wobei festzustellen war, dass ein Kern die ganze Zeit zu 100 % ausgelastet war. Selbst jetzt 20 Minuten nach Beenden des Szenarios und ohne, dass wir danach ein weiteres gestartet haben, ist das Orderbuch immer noch nicht vollständig abgearbeitet und die Einträge entsprechend gematched. 

Wir haben eine Vermutung woher die Performance Probleme im Wesentlichen stammen können. Node.js ist leider nur Single Threaded. Durch das Einstellen von Orders und diverser API Anfragen ist dieser scheinbar schon sehr stark ausgelastet, weshalb er mit dem Matching und allen nachfolgenden Schritten wie zum Beispiel einem Clearing gar nicht mehr hinterherkommt. Bei den anderen Clients bzw. Brookern zeigt sich das Problem auch. Hier laden z.B. die Frontends nur sehr langsam, wenn synchron Kurswerte abgefragt werden müssen, da der eine Thread der Börse dementsprechend mit anderen Aufgaben beschäftigt ist. 

Lasst uns doch bitte mal gemeinsam diskutieren, wie wir hiermit umgehen können. Schließlich haben die beschriebenen Probleme Auswirkungen auf das gesamte Projekt und nicht nur auf einzelne Gruppen. 

Wir freuen uns über eure Nachricht. Danke für eure Unterstützung!
