### ISSUE TITLE
Festlegung Frontend

### ISSUE THREAD

**Issue by Salocinf** [Stonks2Moon/Boerse#9]
- machen wir ein Frontend?
- Wenn ja, was soll da rein?

**Comment by JeannineB** [comment]
- Authentifizierung
- Unterbrechungsmöglichkeit
- neue Tokens für weitere Broker
- Kurse Darstellung
- Abbildung aktuelles Orderbuch
- Gewinn- und Umsatzdarstellung, Anzahl Transaktionen --> Statistiken

**Comment by TimoScheuermann** [comment]
Framework wird Vue.js sein
